/**
 * Device fingerprinting — combines multiple stable signals into a single
 * hashed identifier. Used ONLY for identification (matching a returning
 * device), never for authentication. Values are hashed before storage so the
 * raw signals are not persisted.
 */
import crypto from 'crypto';

export interface FingerprintSignals {
  hostname?: string;
  platform?: string;
  arch?: string;
  /** A persistent per-install id generated by the CLI. */
  deviceId?: string;
  username?: string;
}

/** Produce a stable, hashed fingerprint from several signals (order-independent). */
export function computeFingerprint(signals: FingerprintSignals): string {
  const parts = [
    signals.deviceId ?? '',
    (signals.hostname ?? '').toLowerCase(),
    (signals.platform ?? '').toLowerCase(),
    (signals.arch ?? '').toLowerCase(),
    (signals.username ?? '').toLowerCase(),
  ];
  // Require at least two non-empty signals so a single property can't define identity.
  const nonEmpty = parts.filter((p) => p.length > 0);
  const material = nonEmpty.length >= 2 ? parts.join('|') : parts.join('|') + '|weak';
  return crypto.createHash('sha256').update(material).digest('hex');
}

/** Count how many distinct signals were provided (quality indicator). */
export function fingerprintStrength(signals: FingerprintSignals): number {
  return Object.values(signals).filter((v) => typeof v === 'string' && v.length > 0).length;
}
